[mypy]
python_version = 3.13
strict = True
warn_unused_configs = True
mypy_path = src

[mypy-trl.*]
ignore_missing_imports = True

[mypy-unsloth.*]
ignore_missing_imports = True

[mypy-transformers.*]
ignore_missing_imports = True

[mypy-datasets.*]
ignore_missing_imports = True

[mypy-torch.*]
ignore_missing_imports = True
